openapi: 3.0.0
info:
  title: «Сломанное» API
  version: v1
components:
  schemas:
    Product:
      type: object
      description: Продукт
      properties:
        name:
          type: string
          description: Название товара
        description:
          type: string
          description: Описание товара
        vendor_code:
          type: number
          description: Артикул
        picture:
          type: string
          format: binary
          description: Изображение
paths:
  /api/products:
    post:
      summary: Создание продукта
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              "$ref": "#/components/schemas/Product"
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Идентификатор созданного продукта
  /api/products/{id}:
    get:
      summary: Получение продукта
      parameters:
        - name: id
          in: query
          description: Идентификатор продукта
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
