openapi: 3.0.0
info:
  title: «Hacked» API
  version: v1
components:
  schemas:
    Product::name:
      type: string
      description: Name
    Product::description:
      type: string
      description: Description
    Product::vendor_code:
      type: number
      description: Vendor code
    Product::picture:
      type: object
      description: Picture
      properties:
        link:
          type: string
          description: File url
        filename:
          type: string
          description: File name
    Product::picture::upload:
      type: string
      format: binary
      description: Picture
paths:
  /api/products:
    post:
      summary: Create product
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name: {"$ref": "#/components/schemas/Product::name"}
                description: {"$ref": "#/components/schemas/Product::description"}
                vendor_code: {"$ref": "#/components/schemas/Product::vendor_code"}
                picture: {"$ref": "#/components/schemas/Product::picture::upload"}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Product ID
  /api/products/{id}:
    get:
      summary: Get product
      parameters:
        - name: id
          in: query
          description: Product ID
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  name: {"$ref": "#/components/schemas/Product::name"}
                  description: {"$ref": "#/components/schemas/Product::description"}
                  vendor_code: {"$ref": "#/components/schemas/Product::vendor_code"}
                  picture: {"$ref": "#/components/schemas/Product::picture"}
